In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import os


In [12]:

base_dir = os.path.abspath(os.path.join('..', 'csv'))

file_path = os.path.join(base_dir, 'homeprices.csv')
df = pd.read_csv(file_path)
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [13]:
dummies = pd.get_dummies(df.town)

In [14]:
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [15]:
df_dummies = pd.concat([df, dummies], axis='columns')
df_dummies

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [16]:
df_dummies.drop(['town','west windsor'],axis=1,inplace=True)
df_dummies

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [7]:
x = df_dummies.drop('price',axis='columns')
x

town  area  monroe township  robinsville  west windsor
0   monroe township  2600             True        False         False
1   monroe township  3000             True        False         False
2   monroe township  3200             True        False         False
3   monroe township  3600             True        False         False
4   monroe township  4000             True        False         False
5      west windsor  2600            False        False          True
6      west windsor  2800            False        False          True
7      west windsor  3300            False        False          True
8      west windsor  3600            False        False          True
9       robinsville  2600            False         True         False
10      robinsville  2900            False         True         False
11      robinsville  3100            False         True         False
12      robinsville  3600            False         True         False

In [8]:
y = df_dummies.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [9]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x,y)

ValueError: could not convert string to float: 'monroe township'

In [11]:
# with 3400 sq.ft area in west windsor predict price of a home
reg.predict([[3400,0,0]])

/home/mind/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [2]:
# with 2800 sq.ft area in robinsville predict price of a home
reg.predict([[2800,0,1]])

NameError: name 'reg' is not defined

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
dfle = df

In [16]:
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [17]:
x = dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [18]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ohe = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])  # Apply OneHotEncoder to the first column ('town')
    ],
    remainder='passthrough'  # Keep other columns as they are
)

In [10]:
x = ohe.fit_transform(x)
x

NameError: name 'ohe' is not defined

In [21]:
reg.fit(x,y)

LinearRegression()

In [22]:
reg.predict([[0,0,1,3400]])

array([681241.6684584])

In [23]:
r2_score = reg.score(x, y)
print("R^2 Score:", r2_score)

R^2 Score: 0.9573929037221873
